# .github/workflows/deploy.yml

name: Deploy Website to InfinityFree (huynhchibao.42web.io)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10        # tránh bị treo job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          
      - name: Set Git to quiet mode
        run: git config --global advice.statusHints false

      - name: Upload via FTP to InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftpupload.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /htdocs/
          state-name: .ftp-deploy-sync-state.json     
          dangerous-clean-slate: false               
          exclude: |
            **/.git/**
            **/.github/**
            **/.gitignore
            **/.vscode/**
            **/*.md
            **/deploy.yml
            **/.ftp-deploy-sync-state.json
            **/LICENSE*
            **/composer.*                             
            **/node_modules/**
            **/package*.json
            **/yarn*.lock
            **/pnpm-lock.yaml
